### ISSUE TITLE
Upgrading to the new Skyrim release

### ISSUE THREAD

**Issue by BadDogSkyrim** [schlangster/skyui#75]
I'm hearing bad news about the new skyrim release--that SkyUI may not be upgraded to support it. Since I use lots of mods that depend on MCM, and that's a SkyUI thing (right?), I'd be pretty unhappy if that were the case.

So I'd like to volunteer to help with an upgrade. I've got good coding skills and I'm pretty familiar with general Skyrim modding. I don't know anything about .AS files but have no difficulty learning a new language. I built a whole Logo/Turtle Graphics system in C++ some years back, tho I've done nothing in that language since.

**Comment by mlheur** [comment]
Me too, I'm in.  I've tweaked my own SkyUI to add more column sorting on the inventory and I've run a few builds.  I don't have much experience with git but I'm no stranger to version control systems, branches and releases.

I know that the SkyUI version on the nexus is newer & not in sync with what's up here.  I don't think de-compiling the nexus flash files is a good idea, if we can get the source used to make the nexus build re-synced here then we can be off to the races.

BTW: Action Script is a C derived language, if you can code in C/C++ then you can pick it up with no additional training - just need to know the API references.
