### ISSUE TITLE
SkyUI Permission Request - Beyond Skyrim

### ISSUE THREAD

**Issue by Elscrux** [schlangster/skyui#88]
Hello,
we from [Beyond Skyrim](https://beyondskyrim.org/) want to add custom map markers and custom quest artwork to our mods.
To ensure compatibility with SkyUI, we want to use it as a base, as pretty much everyone is using SkyUI.

We would like to request permission to edit and distribute SkyUI files in our mods (all noncommercial).

I'd appreciate a response!
Elscrux

**Comment by Mardoxx** [comment]
No.

The map system is extensible, however. Just override map markers swf.

**Comment by Elscrux** [comment]
Thanks for the answer. I appreciate your decision, however I have further questions.

Are you referencing mapMarkerArt.swf? To my knowledge, this is a SkyUI file. So would we be allowed to override SkyUI files?

Maybe I was not clear in my message. We don't want to publish the mod SkyUI in our mod. We only want to override some SkyUI based files (map.swf, mapMarkerArt.swf, quest_journal.swf, buttonart.swf and configpanel.swf) so players don't have to download a patch for it and both mods can be played with alongside each other without issues, basically like every other patch, but built-in. (We have a working version of that already internally)

Or are you saying that we are not allowed in any way to use SkyUI files as a base to make our custom map marker implementation and as such no patch is possible?

**Comment by Elscrux** [comment]
@Mardoxx It's me again, sorry, I don't mean to spam. We'd just like to get this settled, so we can decide if we can do an upcoming release with or without custom map markers 😃

I think my message was a bit unclear, as I explained above in detail we only wish to include a built-in patch for our [mod(s)](https://www.nexusmods.com/skyrimspecialedition/mods/10917) and SkyUI to make the life of a lot of mod users easier. Furthermore, this would avoid the need of two kinds of custom map marker and quest art implementation on our side, which would be nice.

As many other mods do this, I honestly didn't expect any issues with permissions, but of course we wanted to ask for permission first, as we have no interest in beginning a dispute in any way. Is it that all the other mods "illegally" build their mods on top of SkyUI or is the problem my wording from before that may have implied that we want to "republish" SkyUI in our mod, which is not the case?

**Comment by Hannes821** [comment]
There are several teams here that want a clear answer, and several projects that are affected.
DANKESCHÖN.

**Comment by Hannes821** [comment]
@Mardoxx so "extensible" means we can modify them and make them compatible to yours.
